import Logo from "./_components/Logo";
import Navigation from "./_components/Navigation";
import "@/app/_styles/globals.css";

import { Josefin_Sans } from "next/font/google"

const josefin = Josefin_Sans({
  subsets : ["latin"],
  display : "swap",
  variable : "--font-josefin",
  weight : ["400", "500", "700"]

})


export const metadata = {
  title: {
    template : "%s | The Wild Oasis",
    default : "The Wild Oasis"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${josefin.className} bg-primary-950 text-primary-100 min-h-screen`} >
      <header>
          <Logo />
          <Navigation />
        </header>
        <main>{children}</main>
        <footer>Copyright by The Wild Oasis</footer>
      </body>
    </html>
  );
}
